[functions.send-user-created-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-user-created-email/deno.json"
entrypoint = "./functions/send-user-created-email/index.ts"
[functions.admin-delete-user]
enabled = true
verify_jwt = true
import_map = "./functions/admin-delete-user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/admin-delete-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/admin-delete-user/*.html" ]

[functions.add-user-to-group]
enabled = true
verify_jwt = true
import_map = "./functions/add-user-to-group/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/add-user-to-group/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/add-user-to-group/*.html" ]

[functions.verify-user]
enabled = true
verify_jwt = true
import_map = "./functions/verify-user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/verify-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/verify-user/*.html" ]

[functions.reset-user-password]
enabled = true
verify_jwt = true
import_map = "./functions/reset-user-password/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/reset-user-password/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/reset-user-password/*.html" ]

[functions.remove-user-from-group]
enabled = true
verify_jwt = true
import_map = "./functions/remove-user-from-group/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/remove-user-from-group/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/remove-user-from-group/*.html" ]
